### ISSUE TITLE
tendrl-node-agent service failure

### ISSUE THREAD

**Issue by fbalak** [Tendrl/node-agent#224]
`tendrl-node-agent` service fails at first attempt to start. Needs to be restarted. This happens to me every time I reinstall Tendrl.
Tested with `tendrl-node-agent-1.2-02_22_2017_00_01_02.noarch`.

`# systemctl status tendrl-node-agent`
● tendrl-node-agent.service - A python agent local to every managed storage node in the sds cluster
   Loaded: loaded (/usr/lib/systemd/system/tendrl-node-agent.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since St 2017-02-22 09:38:09 UTC; 2min 44s ago
 Main PID: 11545 (code=exited, status=1/FAILURE)

```
úno 22 09:38:08 hostname systemd[1]: tendrl-node-agent.service: main process exited, code=exited, status=1/FAILURE
úno 22 09:38:08 hostname systemd[1]: Unit tendrl-node-agent.service entered failed state.
úno 22 09:38:08 hostname systemd[1]: tendrl-node-agent.service failed.
úno 22 09:38:09 hostname systemd[1]: tendrl-node-agent.service holdoff time over, scheduling restart.
úno 22 09:38:09 hostname systemd[1]: start request repeated too quickly for tendrl-node-agent.service
úno 22 09:38:09 hostname systemd[1]: Failed to start A python agent local to every managed storage node in the sds cluster.
úno 22 09:38:09 hostname systemd[1]: Unit tendrl-node-agent.service entered failed state.
úno 22 09:38:09 hostname systemd[1]: tendrl-node-agent.service failed.
```

`# journalctl _PID=11545`
```
-- Logs begin at St 2017-02-22 09:23:37 UTC, end at St 2017-02-22 09:40:37 UTC. --
úno 22 09:38:08 hostname tendrl-node-agent[11545]: Traceback (most recent call last):
úno 22 09:38:08 hostname tendrl-node-agent[11545]: File "/usr/bin/tendrl-node-agent", line 9, in <module>
úno 22 09:38:08 hostname tendrl-node-agent[11545]: load_entry_point('tendrl-node-agent==1.2', 'console_scripts', 'tendrl-node-agent')()
úno 22 09:38:08 hostname tendrl-node-agent[11545]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
úno 22 09:38:08 hostname tendrl-node-agent[11545]: return get_distribution(dist).load_entry_point(group, name)
úno 22 09:38:08 hostname tendrl-node-agent[11545]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
úno 22 09:38:08 hostname tendrl-node-agent[11545]: return ep.load()
úno 22 09:38:08 hostname tendrl-node-agent[11545]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
úno 22 09:38:08 hostname tendrl-node-agent[11545]: entry = __import__(self.module_name, globals(),globals(), ['__name__'])
úno 22 09:38:08 hostname tendrl-node-agent[11545]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/__init__.py", line 25, in <module>
úno 22 09:38:08 hostname tendrl-node-agent[11545]: from tendrl.node_agent.objects.message import Message
úno 22 09:38:08 hostname tendrl-node-agent[11545]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/objects/message/__init__.py", line 2, in <module>
úno 22 09:38:08 hostname tendrl-node-agent[11545]: from tendrl.commons.message import Message as message
úno 22 09:38:08 hostname tendrl-node-agent[11545]: File "/usr/lib/python2.7/site-packages/tendrl/commons/message.py", line 6, in <module>
úno 22 09:38:08 hostname tendrl-node-agent[11545]: from tendrl.commons.utils.time_utils import now
úno 22 09:38:08 hostname tendrl-node-agent[11545]: File "/usr/lib/python2.7/site-packages/tendrl/commons/utils/time_utils.py", line 2, in <module>
úno 22 09:38:08 hostname tendrl-node-agent[11545]: from pytz import utc
úno 22 09:38:08 hostname tendrl-node-agent[11545]: ImportError: No module named pytz
```

**Comment by r0h4n** [comment]
@TimothyAsir please respond to this, seems like the "pytz" dependency issue that you recently fixed

**Comment by fbalak** [comment]
I tested new packages and I can not make `tendrl-node-agent` service work for more than a second. Restart doesn't help anymore. 
Tested with `tendrl-node-agent-1.2-02_23_2017_00_01_03.noarch`

`# systemctl status tendrl-node-agent`
● tendrl-node-agent.service - A python agent local to every managed storage node in the sds cluster
   Loaded: loaded (/usr/lib/systemd/system/tendrl-node-agent.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Čt 2017-02-23 08:10:44 UTC; 7s ago
  Process: 25082 ExecStart=/usr/bin/tendrl-node-agent (code=exited, status=1/FAILURE)
 Main PID: 25082 (code=exited, status=1/FAILURE)

```
úno 23 08:10:44 hostname systemd[1]: tendrl-node-agent.service: main process exited, code=exited, status=1/FAILURE
úno 23 08:10:44 hostname systemd[1]: Unit tendrl-node-agent.service entered failed state.
úno 23 08:10:44 hostname systemd[1]: tendrl-node-agent.service failed.
úno 23 08:10:44 hostname systemd[1]: tendrl-node-agent.service holdoff time over, scheduling restart.
úno 23 08:10:44 hostname systemd[1]: start request repeated too quickly for tendrl-node-agent.service
úno 23 08:10:44 hostname systemd[1]: Failed to start A python agent local to every managed storage node in the sds cluster.
úno 23 08:10:44 hostname systemd[1]: Unit tendrl-node-agent.service entered failed state.
úno 23 08:10:44 hostname systemd[1]: tendrl-node-agent.service failed.
```

`# journalctl _PID=25082`
```
-- Logs begin at Čt 2017-02-23 07:26:23 UTC, end at Čt 2017-02-23 08:10:44 UTC. --
úno 23 08:10:44 hostname tendrl-node-agent[25082]: Traceback (most recent call last):
úno 23 08:10:44 hostname tendrl-node-agent[25082]: File "/usr/bin/tendrl-node-agent", line 9, in <module>
úno 23 08:10:44 hostname tendrl-node-agent[25082]: load_entry_point('tendrl-node-agent==1.2', 'console_scripts', 'tendrl-node-agent')()
úno 23 08:10:44 hostname tendrl-node-agent[25082]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
úno 23 08:10:44 hostname tendrl-node-agent[25082]: return get_distribution(dist).load_entry_point(group, name)
úno 23 08:10:44 hostname tendrl-node-agent[25082]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
úno 23 08:10:44 hostname tendrl-node-agent[25082]: return ep.load()
úno 23 08:10:44 hostname tendrl-node-agent[25082]: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
úno 23 08:10:44 hostname tendrl-node-agent[25082]: entry = __import__(self.module_name, globals(),globals(), ['__name__'])
úno 23 08:10:44 hostname tendrl-node-agent[25082]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/__init__.py", line 25, in <module>
úno 23 08:10:44 hostname tendrl-node-agent[25082]: from tendrl.node_agent.objects.message import Message
úno 23 08:10:44 hostname tendrl-node-agent[25082]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/objects/message/__init__.py", line 2, in <module>
úno 23 08:10:44 hostname tendrl-node-agent[25082]: from tendrl.commons.message import Message as message
úno 23 08:10:44 hostname tendrl-node-agent[25082]: File "/usr/lib/python2.7/site-packages/tendrl/commons/message.py", line 8, in <module>
úno 23 08:10:44 hostname tendrl-node-agent[25082]: sys.path.remove('/usr/lib64/collectd')
úno 23 08:10:44 hostname tendrl-node-agent[25082]: ValueError: list.remove(x): x not in list
```

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/pull/171

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/pull/167

**Comment by nthomas-redhat** [comment]
I tested this with latest build and don't see this issue any more. Please verify and close

**Comment by fbalak** [comment]
It seems ok --> closed
Tested with tendrl-node-agent-1.2-02_23_2017_15_22_11.noarch.
