### ISSUE TITLE
unit tests fails on ConfigNotFound exception

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/node-agent#245]
All unit tests on master branch fails on ConfigNotFound error, see example of full report of 1st issue which failed in this way:

```
____________ ERROR collecting tendrl/node_agent/tests/test_base.py _____________
tendrl/node_agent/tests/test_base.py:2: in <module>
    from tendrl.node_agent.discovery.platform import base
tendrl/node_agent/__init__.py:42: in <module>
    NodeAgentNS()
tendrl/node_agent/__init__.py:40: in __init__
    super(NodeAgentNS, self).__init__()
.tox/py27-cover-master/lib/python2.7/site-packages/tendrl/commons/__init__.py:29: in __init__
    self.config = ns_obj.objects.Config()
tendrl/node_agent/objects/config/__init__.py:13: in __init__
    'node-agent',"/etc/tendrl/node-agent/node-agent.conf.yaml")
.tox/py27-cover-master/lib/python2.7/site-packages/tendrl/commons/config.py:21: in load_config
    raise err
E   ConfigNotFound: Configuration for module: node-agent not found at /etc/tendrl/node-agent/node-agent.conf.yaml
------------------------------- Captured stderr --------------------------------
No handlers could be found for logger "tendrl.commons.config"
```

The root cause of this problem seems to be wrong design of configuration loading. When I just try to import `tendrl.node_agent` module, the import fails on ConfigNotFound exception:

```
$ python
Python 2.7.13 (default, Jan 12 2017, 17:59:37) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tendrl
>>> import tendrl.node_agent
No handlers could be found for logger "tendrl.commons.config"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martin/projects/tendrl.org/tendrl-node-agent/tendrl/node_agent/__init__.py", line 42, in <module>
    NodeAgentNS()
  File "/home/martin/projects/tendrl.org/tendrl-node-agent/tendrl/node_agent/__init__.py", line 40, in __init__
    super(NodeAgentNS, self).__init__()
  File "/home/martin/projects/tendrl.org/tendrl-node-agent/.env/lib/python2.7/site-packages/tendrl/commons/__init__.py", line 29, in __init__
    self.config = ns_obj.objects.Config()
  File "/home/martin/projects/tendrl.org/tendrl-node-agent/tendrl/node_agent/objects/config/__init__.py", line 13, in __init__
    'node-agent',"/etc/tendrl/node-agent/node-agent.conf.yaml")
  File "/home/martin/projects/tendrl.org/tendrl-node-agent/.env/lib/python2.7/site-packages/tendrl/commons/config.py", line 21, in load_config
    raise err
tendrl.commons.config.ConfigNotFound: Configuration for module: node-agent not found at /etc/tendrl/node-agent/node-agent.conf.yaml
>>> 

```

This is not a good design, because it makes debugging, unit testing and maintenance in the long term much harder.

**Comment by r0h4n** [comment]
Unit tests written for tendrl services will have to mock all the NS.$object  (eg: NS.config, NS.tendrl_context etc), this will allow unit tests to run without failures from actual file ops or etcd ops.

Regarding the current issue, tendrl services are meant to fail if no config yaml is found, and that is intended because tendrl requires central store at any given time which is provided via config details
