### ISSUE TITLE
tendrl-node-agent service failure

### ISSUE THREAD

**Issue by fbalak** [Tendrl/node-agent#246]
`tendrl-node-agent` service fails after a short time. Tested with two instances of tendrl.
On machine with **gluster**:
tendrl-node-monitoring-1.2.1-03_07_2017_00_37_02.noarch
tendrl-gluster-integration-1.2.1-03_07_2017_04_38_02.noarch
tendrl-commons-1.2.1-03_07_2017_18_02_18.noarch
tendrl-node-agent-1.2.1-03_07_2017_17_07_49.noarch
It returns:
`# systemctl status tendrl-node-agent`
● tendrl-node-agent.service - A python agent local to every managed storage node in the sds cluster
   Loaded: loaded (/usr/lib/systemd/system/tendrl-node-agent.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2017-03-07 13:15:27 UTC; 17s ago
  Process: 25705 ExecStart=/usr/bin/tendrl-node-agent (code=exited, status=1/FAILURE)
 Main PID: 25705 (code=exited, status=1/FAILURE)

```
Mar 07 13:15:26 hostname systemd[1]: tendrl-node-agent.service: main process exited, code=exited, status=1/FAILURE
Mar 07 13:15:26 hostname systemd[1]: Unit tendrl-node-agent.service entered failed state.
Mar 07 13:15:26 hostname systemd[1]: tendrl-node-agent.service failed.
Mar 07 13:15:27 hostname systemd[1]: tendrl-node-agent.service holdoff time over, scheduling restart.
Mar 07 13:15:27 hostname systemd[1]: start request repeated too quickly for tendrl-node-agent.service
Mar 07 13:15:27 hostname systemd[1]: Failed to start A python agent local to every managed storage node in the sds cluster.
Mar 07 13:15:27 hostname systemd[1]: Unit tendrl-node-agent.service entered failed state.
Mar 07 13:15:27 hostname systemd[1]: tendrl-node-agent.service failed.
```

`# journalctl _PID=25705`
```
-- Logs begin at Tue 2017-03-07 12:36:42 UTC, end at Tue 2017-03-07 13:15:42 UTC. --
Mar 07 13:15:26 hostname tendrl-node-age[25705]: Starting new HTTP connection (1): hostname-server
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: Starting new HTTP connection (1): hostname-server
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: Traceback (most recent call last):
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: File "/usr/bin/tendrl-node-agent", line 9, in <module>
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: load_entry_point('tendrl-node-agent==1.2.1', 'console_scripts', 'tendrl-node-agent')()
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/manager/__init__.py", line 88, in main
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: tendrl_ns.node_context.save()
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: File "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py", line 42, in save
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: current_obj = self.load()
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: File "/usr/lib/python2.7/site-packages/tendrl/commons/objects/__init__.py", line 60, in load
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: result = tendrl_ns.etcd_orm.read(cls_etcd())
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: File "/usr/lib/python2.7/site-packages/tendrl/commons/etcdobj/__init__.py", line 96, in read
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: etcd_resp = self.client.read(item['key'], quorum=True)
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 562, in read
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: timeout=timeout)
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 874, in wrapper
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: return self._handle_server_response(response)
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: File "/usr/lib/python2.7/site-packages/etcd/client.py", line 954, in _handle_server_response
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: etcd.EtcdError.handle(r)
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 304, in handle
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: raise exc(msg, payload)
Mar 07 13:15:26 hostname tendrl-node-agent[25705]: etcd.EtcdKeyNotFound: Key not found : /nodes
```

On machine with **centos**:
centos-release-ceph-jewel-1.0-1.el7.centos.noarch
ceph-base-10.2.3-0.el7.x86_64
ceph-common-10.2.3-0.el7.x86_64
ceph-osd-10.2.3-0.el7.x86_64
ceph-selinux-10.2.3-0.el7.x86_64
libcephfs1-10.2.3-0.el7.x86_64
python-cephfs-10.2.3-0.el7.x86_64
tendrl-ceph-integration-1.2.1-03_07_2017_06_35_03.noarch
tendrl-commons-1.2.1-03_07_2017_18_02_18.noarch
tendrl-node-agent-1.2.1-03_07_2017_17_07_49.noarch
tendrl-node-monitoring-1.2.1-03_07_2017_00_37_02.noarch

● tendrl-node-agent.service - A python agent local to every managed storage node in the sds cluster
   Loaded: loaded (/usr/lib/systemd/system/tendrl-node-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-03-07 12:48:00 UTC; 3min 26s ago
 Main PID: 32049 (tendrl-node-age)
   CGroup: /system.slice/tendrl-node-agent.service
           └─32049 /usr/bin/python /usr/bin/tendrl-node-agent

```
Mar 07 12:51:18 hostname tendrl-node-agent[32049]: TypeError: argument of type 'NoneType' is not iterable
Mar 07 12:51:25 hostname tendrl-node-age[32049]: Traceback (most recent call last):
                                                                                         File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 151, in _run
                                                                                           self._server.run()...
Mar 07 12:51:25 hostname tendrl-node-agent[32049]: Traceback (most recent call last):
Mar 07 12:51:25 hostname tendrl-node-agent[32049]: File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 151, in _run
Mar 07 12:51:25 hostname tendrl-node-agent[32049]: self._server.run()
Mar 07 12:51:25 hostname tendrl-node-agent[32049]: File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 111, in run
Mar 07 12:51:25 hostname tendrl-node-agent[32049]: self._acceptor()
Mar 07 12:51:25 hostname tendrl-node-agent[32049]: File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 94, in _acceptor
Mar 07 12:51:25 hostname tendrl-node-agent[32049]: not in raw_job['node_ids']:
Mar 07 12:51:25 hostname tendrl-node-agent[32049]: TypeError: argument of type 'NoneType' is not iterable
```

**Comment by shtripat** [comment]
@r0h4n The issue seems to be related to one reported at https://github.com/Tendrl/commons/commit/59953a112639f6946636deb9c8171996093f80b1#diff-fbc8ea2e973a12d3591504a5230f8186R27
