### ISSUE TITLE
Message handler gives error TypeError: read_socket()

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node-agent#279]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib64/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
TypeError: read_socket() takes exactly 2 arguments (3 given)
Tue Mar 14 17:52:43 2017 <Greenlet at 0x7fa74d0abeb0: _handle_and_close_when_done(<bound method MessageHandler.read_socket of <Messa, <bound method StreamServer.do_close of <StreamServ, (<socket at 0x7fa74d003a90 fileno=[Errno 9] Bad fi)> failed with TypeError

read_socket function should take three parameter but it takes only two.third one is args.

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat we can close this, this is fixed
