### ISSUE TITLE
node-agent - NameError: global name 'NS' is not defined

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/node-agent#372]
Following error could be found in `tendrl-node-agent` log:
```
Apr 10 11:01:55 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: 2017-04-10 11:01:55.381423+00:00 - node_monitoring - /usr/lib/python2.7/site-packages/tendrl/commons/objects/node/atoms/cmd/__init__.py:23 - run - INFO - e90a81ec-ccf3-4256-9f3e-3f24c45de009:Executing config_manager dbpush '{"master_name": "ltrilety-usm1-server.usmqe.lab.eng.brq.redhat.com", "interval": 600}' on node ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com
Apr 10 11:01:55 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-age[10250]: 2017-04-10 11:01:55.381423+00:00 - node_monitoring - /usr/lib/python2.7/site-packages/tendrl/commons/objects/node/atoms/cmd/__init__.py:23 - run - INFO - e90a81ec-ccf3-4256-9f3e-3f24c45de009:Executing config_manager dbpush '{"master_name": "ltrilety-usm1-server.usmqe.lab.eng.brq.redhat.com", "interval": 600}' on node ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com python[11149]: ansible-basic.py Invoked with warn=True executable=None chdir=None _raw_params=systemctl show -p LoadState None.service removes=None creates=None _uses_shell=False
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-age[10250]: 2017-04-10 11:01:56.752660+00:00 - node_monitoring - /usr/lib/python2.7/site-packages/tendrl/commons/objects/node/atoms/cmd/__init__.py:57 - run - INFO - e90a81ec-ccf3-4256-9f3e-3f24c45de009:Failed to execute config_manager dbpush '{"master_name": "ltrilety-usm1-server.usmqe.lab.eng.brq.redhat.com", "interval": 600}' on node ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com.Error Traceback (most recent call last):
                                                                                         File "/usr/bin/config_manager", line 66, in <module>
                                                                                           main()
                                                                                         File "/usr/bin/config_manager", line 61, in main
                                                                                           'collectd'
                                                                                         File "/usr/lib/python2.7/site-packages/tendrl/commons/utils/service.py", line 79, in restart
                                                                                           return self.__run_module(attr)
                                                                                         File "/usr/lib/python2.7/site-packages/tendrl/commons/utils/service.py", line 28, in __run_module
                                                                                           publisher=NS.publisher_id,
                                                                                       NameError: global name 'NS' is not defined
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: 2017-04-10 11:01:56.752660+00:00 - node_monitoring - /usr/lib/python2.7/site-packages/tendrl/commons/objects/node/atoms/cmd/__init__.py:57 - run - INFO - e90a81ec-ccf3-4256-9f3e-3f24c45de009:Failed to execute config_manager dbpush '{"master_name": "ltrilety-usm1-server.usmqe.lab.eng.brq.redhat.com", "interval": 600}' on node ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com.Error Traceback (most recent call last):
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: File "/usr/bin/config_manager", line 66, in <module>
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: main()
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: File "/usr/bin/config_manager", line 61, in main
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: 'collectd'
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: File "/usr/lib/python2.7/site-packages/tendrl/commons/utils/service.py", line 79, in restart
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: return self.__run_module(attr)
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: File "/usr/lib/python2.7/site-packages/tendrl/commons/utils/service.py", line 28, in __run_module
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: publisher=NS.publisher_id,
Apr 10 11:01:56 ltrilety-usm1-gl1.usmqe.lab.eng.brq.redhat.com tendrl-node-agent[10250]: NameError: global name 'NS' is not defined
```

Used packages:
tendrl-commons-1.2.2-04_10_2017_04_42_05.noarch
tendrl-node-agent-1.2.2-04_10_2017_00_01_03.noarch
tendrl-node-monitoring-1.2.2-04_10_2017_16_13_14.noarch

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/pull/377

Let me know if the issue persists
