### ISSUE TITLE
Remove ceph related bits.

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/node-agent#668]
Ceph related bits not removed from node-agent manager file is causing node-agent to break.

**Comment by nnDarshan** [comment]
Its failing with:
Load definitions (.yml) for namespace.tendrl.objects.TendrlContextTraceback (most recent call last):
  File "/usr/bin/tendrl-node-agent", line 9, in <module>
    load_entry_point('tendrl-node-agent==1.5.4', 'console_scripts', 'tendrl-node-agent')()
  File "/usr/lib/python2.7/site-packages/tendrl/node_agent/manager/__init__.py", line 81, in main
    'ceph_provisioner']
KeyError: 'ceph_provisioner'
