### ISSUE TITLE
collectd: SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/node-agent#673]
Description of problem:
Probably after bigger load of data (2 bricks full) there's following error in collectd log:
Nov 15 22:02:27 <hostname> collectd[10477]: Exception in thread Thread-10989:
Nov 15 22:02:27 <hostname> collectd[10477]: Traceback (most recent call last):
Nov 15 22:02:27 <hostname> collectd[10477]: File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
Nov 15 22:02:27 <hostname> collectd[10477]: self.run()
Nov 15 22:02:27 <hostname> collectd[10477]: File "/usr/lib64/python2.7/threading.py", line 765, in run
Nov 15 22:02:27 <hostname> collectd[10477]: self.__target(*self.__args, **self.__kwargs)
Nov 15 22:02:27 <hostname> collectd[10477]: File "/usr/lib64/collectd/gluster/tendrl_gluster_brick_disk_stats.py", line 181, in populate_disk_det
Nov 15 22:02:27 <hostname> collectd[10477]: self.get_brick_devices(brick_path)
Nov 15 22:02:27 <hostname> collectd[10477]: File "/usr/lib64/collectd/gluster/tendrl_gluster_brick_disk_stats.py", line 94, in get_brick_devices
Nov 15 22:02:27 <hostname> collectd[10477]: return self.fetch_brick_devices(brick_path)
Nov 15 22:02:27 <hostname> collectd[10477]: File "/usr/lib64/collectd/gluster/tendrl_gluster_brick_disk_stats.py", line 70, in fetch_brick_device
Nov 15 22:02:27 <hostname> collectd[10477]: brick_path.replace('/', '_').replace("_", "", 1)
Nov 15 22:02:27 <hostname> collectd[10477]: File "/usr/lib64/python2.7/ast.py", line 49, in literal_eval
Nov 15 22:02:27 <hostname> collectd[10477]: node_or_string = parse(node_or_string, mode='eval')
Nov 15 22:02:27 <hostname> collectd[10477]: File "/usr/lib64/python2.7/ast.py", line 37, in parse
Nov 15 22:02:27 <hostname> collectd[10477]: return compile(source, filename, mode, PyCF_ONLY_AST)
Nov 15 22:02:27 <hostname> collectd[10477]: File "<unknown>", line 0
Nov 15 22:02:27 <hostname> collectd[10477]: ^
Nov 15 22:02:27 <hostname> collectd[10477]: SyntaxError: unexpected EOF while parsing

**Comment by r0h4n** [comment]
If tendrl-gluster-integration is not finished syncing the partition details for any given Brick device, the above issue occurs. This happens because the said collectd plugin relies on availability of partition and device details for all Bricks. 

Fixed : https://github.com/Tendrl/node-agent/commit/faec992ae9472490ae1a0346450c597a437a9d4b
